import json, pathlib

bullets = [
  {"slot_index":0,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Built a Python data pipeline converting NoSQL-stored race data into processed telemetry channels for race engineers","intent_id":"intent_work_jaguar_tcs_racing_0","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_16","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":16}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":1,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Developed Atlas_BT, a Python library converting ATLAS binary telemetry to Python data structures for engineer access","intent_id":"intent_work_jaguar_tcs_racing_1","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_2","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":2}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":2,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Ingested live FIA timing feeds into the race data pipeline via Python libraries deployed on-site and cloud","intent_id":"intent_work_jaguar_tcs_racing_2","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_0","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":0}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":3,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Modelled RESS battery and tyre degradation systems in MATLAB to support race strategy simulation and systems design","intent_id":"intent_work_jaguar_tcs_racing_3","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_3","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":3}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":4,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Authored Python strategy scripts used in live race production contexts to inform real-time tactical decisions","intent_id":"intent_work_jaguar_tcs_racing_4","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_5","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":5}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":5,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Deployed race data services to Azure cloud infrastructure, expanding remote analysis and monitoring capabilities","intent_id":"intent_work_jaguar_tcs_racing_5","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_7","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":7}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":6,"section":"work_experience","subsection":"Jaguar TCS Racing","text":"Maintained Azure DevOps work items to align software delivery with stakeholder requirements across sprint cycles","intent_id":"intent_work_jaguar_tcs_racing_6","provenance":{"primary_claim_id":"work_jaguar_tcs_racing_18","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Jaguar TCS Racing","fact_index":18}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":0,"section":"work_experience","subsection":"Republic of Singapore Navy","text":"Trained reservists in 4-stroke and 2-stroke engine operation through structured technical instruction sessions","intent_id":"intent_work_republic_of_singapore_navy_0","provenance":{"primary_claim_id":"work_republic_of_singapore_navy_1","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Republic of Singapore Navy","fact_index":1}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":1,"section":"work_experience","subsection":"Republic of Singapore Navy","text":"Led a team of up to 10 personnel, coordinating operations and maintaining readiness across naval service duties","intent_id":"intent_work_republic_of_singapore_navy_1","provenance":{"primary_claim_id":"work_republic_of_singapore_navy_4","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Republic of Singapore Navy","fact_index":4}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":2,"section":"work_experience","subsection":"Republic of Singapore Navy","text":"Participated in helicopter firefighting operations, coordinating with crew under high-pressure emergency conditions","intent_id":"intent_work_republic_of_singapore_navy_2","provenance":{"primary_claim_id":"work_republic_of_singapore_navy_0","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Republic of Singapore Navy","fact_index":0}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":0,"section":"work_experience","subsection":"Travelindr","text":"Steered product development as co-founder, running focus-group research and UI mockup creation to shape the roadmap","intent_id":"intent_work_travelindr_0","provenance":{"primary_claim_id":"work_travelindr_0","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Travelindr","fact_index":0}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":1,"section":"work_experience","subsection":"Travelindr","text":"Conducted focus-group discussions to surface user insights and inform iterative UI mockup refinements","intent_id":"intent_work_travelindr_1","provenance":{"primary_claim_id":"work_travelindr_1","secondary_claim_ids":[],"source_ref":{"source":".cv-work-experience.json","org":"Travelindr","fact_index":1}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":0,"section":"technical_projects","subsection":"F1 Race Strategy MARL Simulator","text":"Engineered a multi-agent DQN race strategy simulator with an LLM autoresearch loop for hyperparameter optimisation","intent_id":"intent_proj_f1_race_strategy_marl_simulator_0","provenance":{"primary_claim_id":"proj_f1_strategysimulator_0","secondary_claim_ids":[],"source_ref":{"source":".cv-harvest-store.json","project_name":"F1_StrategySimulator","bullet_index":0}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":1,"section":"technical_projects","subsection":"F1 Race Strategy MARL Simulator","text":"Implemented real-time and batch data pipelines over fastF1 data to evaluate pit stop strategy and tyre decisions","intent_id":"intent_proj_f1_race_strategy_marl_simulator_1","provenance":{"primary_claim_id":"proj_f1_strategysimulator_2","secondary_claim_ids":[],"source_ref":{"source":".cv-harvest-store.json","project_name":"F1_StrategySimulator","bullet_index":2}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":0,"section":"technical_projects","subsection":"Agentic CV & Cover Letter Pipeline","text":"Architected a Python multi-agent LLM pipeline orchestrating sub-agents for JD analysis and automated CV tailoring","intent_id":"intent_proj_agentic_cv_cover_letter_pipeline_0","provenance":{"primary_claim_id":"proj_cv_coverletter_generator_agentic_pipeline_0","secondary_claim_ids":[],"source_ref":{"source":".cv-harvest-store.json","project_name":"CV_CoverLetter_Generator_Agentic_Pipeline","bullet_index":0}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":0,"section":"technical_projects","subsection":"Aerodynamic Concept RAG Analyser","text":"Built a RAG pipeline indexing arXiv aerodynamics papers in a vector database for LLM-synthesised concept evaluation","intent_id":"intent_proj_aerodynamic_concept_rag_analyser_0","provenance":{"primary_claim_id":"proj_aerodynamic_rag_analyser_0","secondary_claim_ids":[],"source_ref":{"source":".cv-harvest-store.json","project_name":"aerodynamic_RAG__analyser","bullet_index":0}},"source":"rephrasing","rephrase_generation":0},
  {"slot_index":1,"section":"technical_projects","subsection":"Aerodynamic Concept RAG Analyser","text":"Integrated MCP tooling to extend retrieval capabilities with dynamic arXiv ingestion and iterative refinement","intent_id":"intent_proj_aerodynamic_concept_rag_analyser_1","provenance":{"primary_claim_id":"proj_aerodynamic_rag_analyser_2","secondary_claim_ids":[],"source_ref":{"source":".cv-harvest-store.json","project_name":"aerodynamic_RAG__analyser","bullet_index":2}},"source":"rephrasing","rephrase_generation":0},
]

data = {
  "job_id": 5841, "user_id": 1, "session_timestamp": "2026-03-18T11:30:00Z",
  "hidden_projects": [],
  "header_swaps": [
    {"section":"technical_projects","subsection":"F1 Race Strategy MARL Simulator","header_xpath_index":0,"text":"F1 Race Strategy MARL Simulator | Python, PyTorch, DQN, MARL, reinforcement learning, fastF1"},
    {"section":"technical_projects","subsection":"Agentic CV & Cover Letter Pipeline","header_xpath_index":0,"text":"Agentic CV & Cover Letter Pipeline | Python, React, TypeScript, LLMs, agentic systems, NLP"},
    {"section":"technical_projects","subsection":"Aerodynamic Concept RAG Analyser","header_xpath_index":0,"text":"Aerodynamic Concept RAG Analyser | Python, RAG, vector databases, LLMs, MCP, FastAPI"}
  ],
  "approved_bullets": bullets
}

pathlib.Path(r"C:\Code\CV_crawl\.cv-apply-selections-tmp.json").write_text(
    json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
)
print("Written", len(bullets), "bullets")
